version: build.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
nuget:
  disable_publish_on_pr: true
build:
  parallel: true
  verbosity: minimal
cache:
- packages -> **\packages.config
before_build:
- nuget restore -Verbosity quiet
