//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC2Bot.WebSocket.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC2Bot.WebSocket.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DnLfM.
        /// </summary>
        internal static string AlbumNo {
            get {
                return ResourceManager.GetString("AlbumNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vZaFU.
        /// </summary>
        internal static string AlbumYes {
            get {
                return ResourceManager.GetString("AlbumYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des auteurs de quotes\n```{0}```.
        /// </summary>
        internal static string AuthorQuotesList {
            get {
                return ResourceManager.GetString("AuthorQuotesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre d&apos;arguments est incorrect, rematch bro..
        /// </summary>
        internal static string BadArgCount {
            get {
                return ResourceManager.GetString("BadArgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;:protoss:272809554553602049&gt;.
        /// </summary>
        internal static string Emoji_Protoss {
            get {
                return ResourceManager.GetString("Emoji_Protoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;:random:272816235752849409&gt;.
        /// </summary>
        internal static string Emoji_Random {
            get {
                return ResourceManager.GetString("Emoji_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;:terran:272812377513394186&gt;.
        /// </summary>
        internal static string Emoji_Terran {
            get {
                return ResourceManager.GetString("Emoji_Terran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;:zerg:272812425185853441&gt;.
        /// </summary>
        internal static string Emoji_Zerg {
            get {
                return ResourceManager.GetString("Emoji_Zerg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je n&apos;ai pas de quote pour ce joueur..
        /// </summary>
        internal static string NoQuoteFor {
            get {
                return ResourceManager.GetString("NoQuoteFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à My life for Aiur !.
        /// </summary>
        internal static string ProtossQuote {
            get {
                return ResourceManager.GetString("ProtossQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des joueurs envoyée en message privée.&quot;.
        /// </summary>
        internal static string QuoteCommandSendMP {
            get {
                return ResourceManager.GetString("QuoteCommandSendMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour les hommes !.
        /// </summary>
        internal static string RandomQuote {
            get {
                return ResourceManager.GetString("RandomQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kaboom Baby !.
        /// </summary>
        internal static string TerranQuote {
            get {
                return ResourceManager.GetString("TerranQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à REKT, cette commande n&apos;existe pas.
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La réponse est **non**.
        /// </summary>
        internal static string yesno_Non {
            get {
                return ResourceManager.GetString("yesno_Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La réponse est **oui**.
        /// </summary>
        internal static string yesno_Oui {
            get {
                return ResourceManager.GetString("yesno_Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à For the Swarm ♥.
        /// </summary>
        internal static string ZergQuote {
            get {
                return ResourceManager.GetString("ZergQuote", resourceCulture);
            }
        }
    }
}
